In [8]:
data = {
    "PETERBILT": "Combination Long-haul Truck",
    "KENWORTH": "Combination Long-haul Truck",
    "INTERNATIONAL": "Combination Long-haul Truck",
    "ISUZU": "Single Unit Short-haul Truck",
    "HINO": "Single Unit Short-haul Truck",
    "AUTOCAR": "Single Unit Short-haul Truck",
    "ROADMASTER": "Single Unit Short-haul Truck",
    "MACK": "Combination Long-haul Truck",
    "SPARTAN": "Combination Long-haul Truck",
    "WESTERN STAR": "Combination Long-haul Truck",
    "STERLING": "Combination Long-haul Truck",
    "CRANE CARRIER": "Combination Short-haul Truck",
    "HME": "Combination Short-haul Truck",
    "AM GENERAL": "Combination Short-haul Truck",
    "TMC": "Single Unit Long-haul Truck",
    "TICO": "Single Unit Long-haul Truck",
    "WHITE/GMC": "Single Unit Long-haul Truck",
    "ALLIANZ": "Combination Short-haul Truck",
    "MAN TRUCK AND BUS CORPORATION": "Combination Long-haul Truck",
    "CAPACITY": "Single Unit Short-haul Truck",
    "CATERPILLAR": "Single Unit Long-haul Truck",
    "FWD": "Single Unit Short-haul Truck",
    "OSHKOSH": "Combination Short-haul Truck"

}
# Create an empty list to store the matched names
matched_names = []

# Loop through the dictionary and check for "Passenger Car" value
for name, category in data.items():
    if category == 'Single Unit Short-haul Truck':
        matched_names.append(name)

# Convert the list to a single row string separated by commas
matched_names_row = ', '.join(matched_names)

print(matched_names_row)

ISUZU, HINO, AUTOCAR, ROADMASTER, CAPACITY, FWD

In [7]:
data = {
    'OTHER/UNK': 'Other',
    'FORD': 'Passenger Car',
    'PLYMOUTH': 'Passenger Car',
    'CHEVROLET': 'Passenger Car',
    'Unk': 'Other',
    'GMC': 'Passenger Truck',
    'WHITE': 'Light Commercial Truck',
    'INFINITI': 'Passenger Car',
    'MERCEDES-BENZ': 'Passenger Car',
    'VOLKSWAGEN': 'Passenger Car',
    'DODGE': 'Passenger Car',
    'JEEP': 'Passenger Car',
    'ACURA': 'Passenger Car',
    'HONDA': 'Passenger Car',
    'CHRYSLER': 'Passenger Car',
    'CADILLAC': 'Passenger Car',
    'NISSAN': 'Passenger Car',
    'TOYOTA': 'Passenger Car',
    'MAZDA': 'Passenger Car',
    'BMW': 'Passenger Car',
    'HYUNDAI': 'Passenger Car',
    'LEXUS': 'Passenger Car',
    'KIA': 'Passenger Car',
    'SCION': 'Passenger Car',
    'PONTIAC': 'Passenger Car',
    'FREIGHTLINER': 'Light Commercial Truck',
    'RAM': 'Passenger Truck',
    'AUDI': 'Passenger Car',
    'MINI': 'Passenger Car',
    'HINO': 'Medium/Heavy Truck',
    'MITSUBISHI': 'Passenger Car',
    'INTERNATIONAL': 'Medium/Heavy Truck',
    'SUBARU': 'Passenger Car',
    'BUICK': 'Passenger Car',
    'TESLA': 'Passenger Car',
    'MERCURY': 'Passenger Car',
    'LINCOLN': 'Passenger Car',
    'VOLVO': 'Passenger Car',
    'HUMMER': 'Passenger Truck',
    'OLDSMOBILE': 'Passenger Car',
    'SATURN': 'Passenger Car',
    'ISUZU': 'Medium/Heavy Truck',
    'SUZUKI': 'Passenger Car',
    'LAND ROVER': 'Passenger Car',
    'PORSCHE': 'Passenger Car',
    'UNKNOWN': 'Other',
    'JAGUAR': 'Passenger Car',
    'FIAT': 'Passenger Car',
    'GENESIS': 'Passenger Car',
    'SAAB': 'Passenger Car',
    'ALFA ROMEO': 'Passenger Car',
    'GEO': 'Passenger Car',
    'WORKHORSE': 'Light Commercial Truck',
    'AMERICAN LAFRANCE': 'Transit Bus',
    'NORTH AMERICAN BUS INDUSTRIES': 'Transit Bus',
    'PETERBILT': 'Medium/Heavy Truck',
    'MOTOR COACH INDUSTRIES': 'Transit Bus',
    'EL DORADO': 'Transit Bus',
    'NEW FLYER': 'Transit Bus',
    'KENWORTH': 'Medium/Heavy Truck',
    'GILLIG': 'Transit Bus',
    'BLUE BIRD': 'School Bus',
    'AUTOCAR': 'Medium/Heavy Truck',
    'PIERCE': 'Refuse Truck',
    'IC BUS': 'School Bus',
    'PROTERRA': 'Transit Bus',
    'FWD': 'Medium/Heavy Truck',
    'NEOPLAN': 'Transit Bus',
    'OSHKOSH': 'Medium/Heavy Truck',
    'ORION': 'Transit Bus',
    'SEAGRAVE': 'Refuse Truck',
    'STERLING': 'Medium/Heavy Truck',
    'FLXIBLE TRANSIT COACHES': 'Transit Bus',
    'MACK': 'Medium/Heavy Truck',
    'TMC': 'Medium/Heavy Truck',
    'WHITE/GMC': 'Medium/Heavy Truck',
    'KALMAR': 'Light Commercial Truck',
    'PREVOST': 'Transit Bus',
    'MASERATI': 'Passenger Car',
    'BENTLEY': 'Passenger Car',
    'ROLLS-ROYCE': 'Passenger Car',
    'FERRARI': 'Passenger Car',
    'ARBOC': 'Transit Bus',
    'POLESTAR': 'Passenger Car',
    'KOVATCH MOBLIE EQUIPMENT CORP.': 'Other Buses',
    'RIVIAN': 'Passenger Car',
    'THOMAS BUS': 'School Bus',
    'ASTON MARTIN': 'Passenger Car',
    'IC BUS LLC': 'School Bus',
    'KOVATCH': 'Other Buses',
    'SMART': 'Passenger Car',
    'LAMBORGHINI': 'Passenger Car',
    'GREENPOWER MOTOR': 'Transit Bus',
    'CRANE CARRIER': 'Medium/Heavy Truck',
    'BYD COACH AND BUS': 'Transit Bus',
    'ALEXANDER DENNIS': 'Transit Bus',
    'ROADMASTER': 'Medium/Heavy Truck',
    'CATERPILLAR': 'Medium/Heavy Truck',
    'ORANGE EV': 'Transit Bus',
    'VPG': 'Passenger Car',
    'AM GENERAL': 'Medium/Heavy Truck',
    'WESTERN STAR': 'Medium/Heavy Truck',
    'NORTH AMERICAN': 'Transit Bus',
    'SPARTAN': 'Medium/Heavy Truck',
    'MOTOR COACH IND': 'Transit Bus',
    'EMERGENCY ONE': 'Refuse Truck',
    'LUCID': 'Passenger Car',
    'CAPACITY': 'Medium/Heavy Truck',
    'TICO': 'Medium/Heavy Truck',
    'BLUEBIRD': 'School Bus',
    'VAN HOOL': 'Transit Bus',
    'MAN TRUCK AND BUS CORPORATION': 'Medium/Heavy Truck',
    'CRUISE': 'Passenger Car',
    'TROLLEY': 'Transit Bus',
    'LODAL': 'Transit Bus',
    'HME': 'Medium/Heavy Truck',
    'ALLIANZ': 'Medium/Heavy Truck',
    'GLOBAL ENVIRONMENTAL': 'Transit Bus',
    'XOS': 'Transit Bus',
    'BRIGHTDROP': 'Passenger Truck',
    'LOTUS': 'Passenger Car',
    'SPECIAL CONSTRUCTION': 'Other',
    'MG': 'Passenger Car',
    'COUNTRY COACH': 'Motor Home'


}
# Create an empty list to store the matched names
matched_names = []

# Loop through the dictionary and check for "Passenger Car" value
for name, category in data.items():
    if category == 'Refuse Truck':
        matched_names.append(name)

# Convert the list to a single row string separated by commas
matched_names_row = ', '.join(matched_names)

print(matched_names_row)

PIERCE, SEAGRAVE, EMERGENCY ONE